routes/web.php
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home', 'HomeController@index')->name('home');

    //Admin Login
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    //Admin Register
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    //Admin Passwords
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    // Rotas de Banners
    Route::get('banners', 'BannersController@index')->name('banners');
    Route::post('banners/reorder', 'BannersController@sortable')->name('banners.reorder');
    Route::post('banners/store', 'BannersController@store')->name('banners.store');
    Route::post('banners/update/{id}', 'BannersController@update')->name('banners.update.{id}');
    Route::get('banners/editar/{id}', 'BannersController@edit')->name('banners.editar.{id}');
    Route::get('banners/delete/{id}', 'BannersController@destroy')->name('banners.delete.{id}');

    // Rotas de quem somos
    Route::get('about', 'AboutController@index')->name('about');
    Route::post('about/reorder', 'AboutController@sortable')->name('about.reorder');
    Route::post('about/store', 'AboutController@store')->name('about.store');
    Route::post('about/store/{id}', 'AboutController@store')->name('about.store.{id}');

    // Rotas de Banners
    Route::get('bannerscx', 'BannerscxController@index')->name('bannerscx');
    Route::post('bannerscx/reorder', 'BannerscxController@sortable')->name('bannerscx.reorder');
    Route::post('bannerscx/store', 'BannerscxController@store')->name('bannerscx.store');
    Route::post('bannerscx/update/{id}', 'BannerscxController@update')->name('bannerscx.update.{id}');
    Route::get('bannerscx/editar/{id}', 'BannerscxController@edit')->name('bannerscx.editar.{id}');
    Route::get('bannerscx/delete/{id}', 'BannerscxController@destroy')->name('bannerscx.delete.{id}');

    // Rotas de Banners
    Route::get('bannersfr', 'BannersfrController@index')->name('bannersfr');
    Route::post('bannersfr/reorder', 'BannersfrController@sortable')->name('bannersfr.reorder');
    Route::post('bannersfr/store', 'BannersfrController@store')->name('bannersfr.store');
    Route::post('bannersfr/update/{id}', 'BannersfrController@update')->name('bannersfr.update.{id}');
    Route::get('bannersfr/editar/{id}', 'BannersfrController@edit')->name('bannersfr.editar.{id}');
    Route::get('bannersfr/delete/{id}', 'BannersfrController@destroy')->name('bannersfr.delete.{id}');


    // Rotas de Staff
    Route::get('staff', 'StaffController@index')->name('staff');
    Route::post('staff/reorder', 'StaffController@sortable')->name('staff.reorder');
    Route::post('staff/store', 'StaffController@store')->name('staff.store');
    Route::post('staff/update/{id}', 'StaffController@update')->name('staff.update.{id}');
    Route::get('staff/editar/{id}', 'StaffController@edit')->name('staff.editar.{id}');
    Route::get('staff/delete/{id}', 'StaffController@destroy')->name('staff.delete.{id}');

    // Rotas de process
    Route::get('stafftext', 'StaffTextController@index')->name('stafftext');
    Route::post('stafftext/store', 'StaffTextController@store')->name('stafftext.store');
    Route::post('stafftext/store/{id}', 'StaffTextController@store')->name('stafftext.store.{id}');

    // Rotas de PeloMundo
    Route::get('pelomundo', 'PeloMundoController@index')->name('pelomundo');
    Route::post('pelomundo/reorder', 'PeloMundoController@sortable')->name('pelomundo.reorder');
    Route::post('pelomundo/store', 'PeloMundoController@store')->name('pelomundo.store');
    Route::post('pelomundo/update/{id}', 'PeloMundoController@update')->name('pelomundo.update.{id}');
    Route::get('pelomundo/editar/{id}', 'PeloMundoController@edit')->name('pelomundo.editar.{id}');
    Route::get('pelomundo/delete/{id}', 'PeloMundoController@destroy')->name('pelomundo.delete.{id}');

    // Rotas de process
    Route::get('pelomundotext', 'PeloMundoTextController@index')->name('pelomundotext');
    Route::post('pelomundotext/store', 'PeloMundoTextController@store')->name('pelomundotext.store');
    Route::post('pelomundotext/store/{id}', 'PeloMundoTextController@store')->name('pelomundotext.store.{id}');

    // Rotas de process Description
    Route::get('processdesc', 'ProcessDescController@index')->name('processdesc');
    Route::post('processdesc/reorder', 'ProcessDescController@sortable')->name('processdesc.reorder');
    Route::post('processdesc/store', 'ProcessDescController@store')->name('processdesc.store');
    Route::post('processdesc/update/{id}', 'ProcessDescController@update')->name('processdesc.update.{id}');
    Route::get('processdesc/editar/{id}', 'ProcessDescController@edit')->name('processdesc.editar.{id}');
    Route::get('processdesc/delete/{id}', 'ProcessDescController@destroy')->name('processdesc.delete.{id}');

    
    // Rotas processos gráfico
    Route::get('processgrafic', 'ProcessGraficController@index')->name('processgrafic');
    Route::post('processgrafic/reorder', 'ProcessGraficController@sortable')->name('processgrafic.reorder');
    Route::post('processgrafic/store', 'ProcessGraficController@store')->name('processgrafic.store');
    Route::post('processgrafic/update/{id}', 'ProcessGraficController@update')->name('processgrafic.update.{id}');
    Route::get('processgrafic/editar/{id}', 'ProcessGraficController@edit')->name('processgrafic.editar.{id}');
    Route::get('processgrafic/delete/{id}', 'ProcessGraficController@destroy')->name('processgrafic.delete.{id}');


    // Rotas de process
    Route::get('process', 'ProcessController@index')->name('process');
    Route::post('process/reorder', 'ProcessController@sortable')->name('process.reorder');
    Route::post('process/store', 'ProcessController@store')->name('process.store');
    Route::post('process/store/{id}', 'ProcessController@store')->name('process.store.{id}');

    // Rotas de event description
    Route::get('eventdesc', 'EventDescController@index')->name('eventsdesc');
    Route::post('eventdesc/reorder', 'EventDescController@sortable')->name('eventdesc.reorder');
    Route::post('eventdesc/store', 'EventDescController@store')->name('eventdesc.store');
    Route::post('eventdesc/update/{id}', 'EventDescController@update')->name('eventdesc.update.{id}');
    Route::get('eventdesc/editar/{id}', 'EventDescController@edit')->name('eventdesc.editar.{id}');
    Route::get('eventdesc/delete/{id}', 'EventDescController@destroy')->name('eventdesc.delete.{id}');

    // Rotas de event
    Route::get('event', 'EventController@index')->name('event');
    Route::post('event/reorder', 'EventController@sortable')->name('event.reorder');
    Route::post('event/store', 'EventController@store')->name('event.store');
    Route::post('event/store/{id}', 'EventController@store')->name('event.store.{id}');

    // Rotas de event description
    Route::get('campaignsdesc', 'CampaignsDescController@index')->name('campaignsdesc');
    Route::post('campaignsdesc/reorder', 'CampaignsDescController@sortable')->name('campaignsdesc.reorder');
    Route::post('campaignsdesc/store', 'CampaignsDescController@store')->name('campaignsdesc.store');
    Route::post('campaignsdesc/update/{id}', 'CampaignsDescController@update')->name('campaignsdesc.update.{id}');
    Route::get('campaignsdesc/editar/{id}', 'CampaignsDescController@edit')->name('campaignsdesc.editar.{id}');
    Route::get('campaignsdesc/delete/{id}', 'CampaignsDescController@destroy')->name('campaignsdesc.delete.{id}');

    // Rotas de event
    Route::get('campaigns', 'CampaignsController@index')->name('event');
    Route::post('campaigns/reorder', 'CampaignsController@sortable')->name('campaigns.reorder');
    Route::post('campaigns/store', 'CampaignsController@store')->name('campaigns.store');
    Route::post('campaigns/store/{id}', 'CampaignsController@store')->name('campaigns.store.{id}');

    // Rotas de campaigns description
    Route::get('campaignsdesc', 'CampaignsDescController@index')->name('campaignsdesc');
    Route::post('campaignsdesc/reorder', 'CampaignsDescController@sortable')->name('campaignsdesc.reorder');
    Route::post('campaignsdesc/store', 'CampaignsDescController@store')->name('campaignsdesc.store');
    Route::post('campaignsdesc/update/{id}', 'CampaignsDescController@update')->name('campaignsdesc.update.{id}');
    Route::get('campaignsdesc/editar/{id}', 'CampaignsDescController@edit')->name('campaignsdesc.editar.{id}');
    Route::get('campaignsdesc/delete/{id}', 'CampaignsDescController@destroy')->name('campaignsdesc.delete.{id}');

    // Rotas de campaigns
    Route::get('campaigns', 'CampaignsController@index')->name('event');
    Route::post('campaigns/reorder', 'CampaignsController@sortable')->name('campaigns.reorder');
    Route::post('campaigns/store', 'CampaignsController@store')->name('campaigns.store');
    Route::post('campaigns/store/{id}', 'CampaignsController@store')->name('campaigns.store.{id}');

    // Rotas de depositions description
    Route::get('depositionsdesc', 'DepositionsDescController@index')->name('depositionsdesc');

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\Staff;
use App\Http\Controllers\Controller;
use App\Services\StandardService;
use Illuminate\Http\Request;
use App\Http\Requests;
use File;
use Response;
use Redirect;
use Session;

class StaffController extends Controller {

    /**
     * @var StandardService
     */
    protected $standard;

    public function __construct(StandardService $standard) {
        $this->standard = $standard;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $items = Staff::orderBy('order','desc')->get();
        return view('admin.staff.index', compact('items'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     *
     * @return \Illuminate\Http\Response
     */
    // SALVANDO
    public function store(Request $request) {
        try {
            $item = new Staff;

            $image = $this->standard->doUpload($request->file('file_image'), '../_files/staff/', false, false);
            $item->image = $image;

            $item->title = $request->input('title');

            $item->desc = $request->input('desc');

            $item->link_face = $request->input('link_face');

            $item->link_insta = $request->input('link_insta');

            $item->save();

            Session::flash('success', 'Item criado com sucesso!');
        } catch (ValidatorException $e) {

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
        return Redirect::to('/admin/staff')->with('status', 'Cadastro realizado com sucesso!');
    }

    /**
     * @param int $id
     * @return mixed
     */
    public function edit($id = 0) {
        $item = Staff::find($id);
        return view('admin.staff.edit', compact('item'));
    }

    /**
     * @param Request $request
     * @param int $id
     * @return mixed
     */
    public function update(Request $request, $id = 0) {
        try {
            $item = Staff::find($id);

            if (!empty($request->file('file_image'))) {
                File::delete('../_files/staff/' . $item->image);
                $image_name = $this->standard->doUpload($request->file('file_image'), '../_files/staff/', false, false);
                $item->image = $image_name;
            }
            $item->title = $request->input('title');

            $item->desc = $request->input('desc');

            $item->link_face = $request->input('link_face');

            $item->link_insta = $request->input('link_insta');
            
            $item->save();

            Session::flash('success', 'Item atualizado com sucesso!');
        } catch (ValidatorException $e) {

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
        return Redirect::to('/admin/staff')->with('status', 'Imagem atualizada com sucesso!');
    }

    /**
     * @param Request $request
     * @return int
     */
    public function sortable(Request $request) {
        $this->standard->doReorder($request->input('items'), true, new Staff);
        return 2;
    }

    /**
     * @param $id
     * @return int
     */
    public function destroy($id) {
        $item = Staff::find($id);

        if (!empty($item->image))
            File::delete('../_files/staff/' . $item->image);

        $item->delete();
        return Redirect::to('/admin/staff')->with('status', 'Imagem excluída com sucesso!');
    }
    
}

resources/views/admin/staff/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Banners > Editar</h1>
@stop


@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Editar Campos</h3>
            </div>
            <form action="{{ route('admin.staff.update.{id}', array($item->id)) }}" method="POST" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <div class="box-body">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label for="image">Imagem:</label>
                            <div class="upload">
                                <div class="btn btn-primary">Atualizar Imagem</div>
                                <input type="file" class="input-file" id="image" name="file_image" /><br>
                                @if (!empty($item->id))
                                (<a href="{{ asset('_files/staff/' . $item->image) }}" title="ver imagem atual" target="_blank">Ver Imagem Atual</a>)
                                @endif
                            </div>
                            
                            <div class="form-group">
                                <label>Título</label>
                                <input type="text" class="form-control" placeholder="Título" name="title" value="{{ empty($item->title) ? old('title') : $item->title}}">
                            </div>
                            <!-- textarea -->
                            <div class="form-group">
                                <label>Descrição</label>
                                <textarea class="form-control" rows="3" placeholder="Texto corpo" name="desc">{{ empty($item->desc) ? old('desc') : $item->desc}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>Link Facebook</label>
                                <input type="text" class="form-control" placeholder="Título" name="link_face" value="{{ empty($item->link_face) ? old('link_face') : $item->link_face}}">
                            </div>
                            <div class="form-group">
                                <label>Link Instagram</label>
                                <input type="text" class="form-control" placeholder="Título" name="link_insta" value="{{ empty($item->link_insta) ? old('link_insta') : $item->link_insta}}">
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="box-footer">
                    <button class="btn btn-success btn-send pull-right">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('vendor/adminlte/css/main.css')}}">
<!-- include summernote css/js -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
@stop

@section('js')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script>
   $('.summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 150
      });
</script>
@yield('js')
@stop

resources/views/admin/staff/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Staff</h1>
@stop


@section('content')
<div class="row">
    <div class="col-md-8 ">
        <div class="box ">
            <div class="box-header with-border">
                @if (!empty($items))
                <h3 class="box-title">Lista Staff</h3>
                @else
                <h3 class="box-title">Nenhum um item cadastrado</h3>
                @endif
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
                @endif
                <div class="col-md-12 color-palette">
                    <table id="tabela" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Título</th>
                                <th>Imagem</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody class="sortable" data-url="{{route('admin.staff.reorder')}}">
                            @foreach($items as $item)
                            <tr class="ui-state-default" data-id="{{$item->id}}">
                                <td>{{$item->id}}</td>
                                <td>{{$item->title}}</td>
                                <td><img width="80" src="{{asset('_files/staff/'.$item->image)}}"></td>
                                <td>
                                    <div class="btn-group">
                                        <a type="button" class="btn btn-success" href="{{route('admin.staff.editar.{id}', array($item->id))}}" data-toggle="tooltip" data-original-title="Editar"><i class="fa fa-pencil"></i></a>
                                        <a type="link"  class="btn btn-danger" href="{{route('admin.staff.delete.{id}', array($item->id))}}" data-toggle="tooltip" data-original-title="Deletar"><i class="fa fa-trash-o"></i></a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>


                </div>
            </div>
            <!-- /.row -->
        </div>
    </div>
    <div class="col-xs-12 col-md-4">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Adicionar Banner</h3>
            </div>
            <form action="{{ route('admin.staff.store') }}" class="form-table-list" method="POST" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="image">Imagem:</label>
                                <div class="upload">
                                    <div class="btn btn-primary">Adicionar Imagem</div>
                                    <input type="file" class="input-file" id="image" name="file_image" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Nome</label>
                                <input type="text" class="form-control" placeholder="Nome" name="title">
                            </div>
                            <div class="form-group">
                                <label>Descrição</label>
                                <input type="text" class="form-control" placeholder="Descrição" name="desc">
                            </div>
                            <div class="form-group">
                                <label>Facebook</label>
                                <input type="text" class="form-control" placeholder="Facebook" name="link_face">
                            </div>
                            <div class="form-group">
                                <label>Instagram</label>
                                <input type="text" class="form-control" placeholder="Instagram" name="link_insta">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button class="btn btn-success btn-send pull-right">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>    
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('vendor/adminlte/css/main.css')}}">
@stop

@section('js')
<script src="{{ asset('js/jquery-ui.js') }}"></script>
<script>
    <!-- CSRF Token -->
    var csrf = "{{ csrf_token() }}";
    var App = App || {};
    App.sortableGrid = function () {
        $('.sortable').each(function (idx, el) {
            var sortable = $(el);
            var obj = {};
            var url = sortable.attr('data-url');
            sortable.sortable().on('sortupdate', function (event, ui) {
                var items = [];
                sortable.find('.ui-state-default').each(function (i) {
                    var order = sortable.find('.ui-state-default').length - i;
                    obj = {'id': $(this).data('id'), 'order': order};
                    items.push(obj);
                });
                App.reorder(items, url);
            });

            sortable.disableSelection();
        });
    };

    App.reorder = function (items, url) {
        if (items.length > 0) {
            $.ajax({
                url: url,
                headers: {'X-CSRF-Token': csrf},
                type: "POST",
                data: {items: items},
                success: function (data) {

                }
            });
        }
    };
    App.sortableGrid();
</script>
@stop