routes/web.php
<?php

Route::get('/', function () {
    return redirect('/pt');
});

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('home', 'HomeController@index')->name('home');

    //Admin Login
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    //Admin Register
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    //Admin Passwords
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    // Rotas de Banners
    Route::get('banners', 'BannersController@index')->name('banners');
    Route::post('banners/reorder', 'BannersController@sortable')->name('banners.reorder');
    Route::post('banners/store', 'BannersController@store')->name('banners.store');
    Route::post('banners/update/{id}', 'BannersController@update')->name('banners.update.{id}');
    Route::get('banners/editar/{id}', 'BannersController@edit')->name('banners.editar.{id}');
    Route::get('banners/delete/{id}', 'BannersController@destroy')->name('banners.delete.{id}');

    // Rotas de quem somos
    Route::get('about', 'AboutController@index')->name('about');
    Route::post('about/reorder', 'AboutController@sortable')->name('about.reorder');
    Route::post('about/store', 'AboutController@store')->name('about.store');
    Route::post('about/store/{id}', 'AboutController@store')->name('about.store.{id}');

    // Rotas de Banners
    Route::get('bannerscx', 'BannerscxController@index')->name('bannerscx');
    Route::post('bannerscx/reorder', 'BannerscxController@sortable')->name('bannerscx.reorder');
    Route::post('bannerscx/store', 'BannerscxController@store')->name('bannerscx.store');
    Route::post('bannerscx/update/{id}', 'BannerscxController@update')->name('bannerscx.update.{id}');
    Route::get('bannerscx/editar/{id}', 'BannerscxController@edit')->name('bannerscx.editar.{id}');
    Route::get('bannerscx/delete/{id}', 'BannerscxController@destroy')->name('bannerscx.delete.{id}');

    // Rotas de Banners
    Route::get('bannersfr', 'BannersfrController@index')->name('bannersfr');
    Route::post('bannersfr/reorder', 'BannersfrController@sortable')->name('bannersfr.reorder');
    Route::post('bannersfr/store', 'BannersfrController@store')->name('bannersfr.store');
    Route::post('bannersfr/update/{id}', 'BannersfrController@update')->name('bannersfr.update.{id}');
    Route::get('bannersfr/editar/{id}', 'BannersfrController@edit')->name('bannersfr.editar.{id}');
    Route::get('bannersfr/delete/{id}', 'BannersfrController@destroy')->name('bannersfr.delete.{id}');


    // Rotas de Staff
    Route::get('staff', 'StaffController@index')->name('staff');
    Route::post('staff/reorder', 'StaffController@sortable')->name('staff.reorder');
    Route::post('staff/store', 'StaffController@store')->name('staff.store');
    Route::post('staff/update/{id}', 'StaffController@update')->name('staff.update.{id}');
    Route::get('staff/editar/{id}', 'StaffController@edit')->name('staff.editar.{id}');
    Route::get('staff/delete/{id}', 'StaffController@destroy')->name('staff.delete.{id}');

    // Rotas de process
    Route::get('stafftext', 'StaffTextController@index')->name('stafftext');
    Route::post('stafftext/store', 'StaffTextController@store')->name('stafftext.store');
    Route::post('stafftext/store/{id}', 'StaffTextController@store')->name('stafftext.store.{id}');

    // Rotas de PeloMundo
    Route::get('pelomundo', 'PeloMundoController@index')->name('pelomundo');
    Route::post('pelomundo/reorder', 'PeloMundoController@sortable')->name('pelomundo.reorder');
    Route::post('pelomundo/store', 'PeloMundoController@store')->name('pelomundo.store');
    Route::post('pelomundo/update/{id}', 'PeloMundoController@update')->name('pelomundo.update.{id}');
    Route::get('pelomundo/editar/{id}', 'PeloMundoController@edit')->name('pelomundo.editar.{id}');
    Route::get('pelomundo/delete/{id}', 'PeloMundoController@destroy')->name('pelomundo.delete.{id}');

    // Rotas de process
    Route::get('pelomundotext', 'PeloMundoTextController@index')->name('pelomundotext');
    Route::post('pelomundotext/store', 'PeloMundoTextController@store')->name('pelomundotext.store');
    Route::post('pelomundotext/store/{id}', 'PeloMundoTextController@store')->name('pelomundotext.store.{id}');

    // Rotas de process Description
    Route::get('processdesc', 'ProcessDescController@index')->name('processdesc');
    Route::post('processdesc/reorder', 'ProcessDescController@sortable')->name('processdesc.reorder');
    Route::post('processdesc/store', 'ProcessDescController@store')->name('processdesc.store');
    Route::post('processdesc/update/{id}', 'ProcessDescController@update')->name('processdesc.update.{id}');
    Route::get('processdesc/editar/{id}', 'ProcessDescController@edit')->name('processdesc.editar.{id}');
    Route::get('processdesc/delete/{id}', 'ProcessDescController@destroy')->name('processdesc.delete.{id}');

    
    // Rotas processos gráfico
    Route::get('processgrafic', 'ProcessGraficController@index')->name('processgrafic');
    Route::post('processgrafic/reorder', 'ProcessGraficController@sortable')->name('processgrafic.reorder');
    Route::post('processgrafic/store', 'ProcessGraficController@store')->name('processgrafic.store');
    Route::post('processgrafic/update/{id}', 'ProcessGraficController@update')->name('processgrafic.update.{id}');
    Route::get('processgrafic/editar/{id}', 'ProcessGraficController@edit')->name('processgrafic.editar.{id}');
    Route::get('processgrafic/delete/{id}', 'ProcessGraficController@destroy')->name('processgrafic.delete.{id}');


    // Rotas de process
    Route::get('process', 'ProcessController@index')->name('process');
    Route::post('process/reorder', 'ProcessController@sortable')->name('process.reorder');
    Route::post('process/store', 'ProcessController@store')->name('process.store');
    Route::post('process/store/{id}', 'ProcessController@store')->name('process.store.{id}');

    // Rotas de event description
    Route::get('eventdesc', 'EventDescController@index')->name('eventsdesc');
    Route::post('eventdesc/reorder', 'EventDescController@sortable')->name('eventdesc.reorder');
    Route::post('eventdesc/store', 'EventDescController@store')->name('eventdesc.store');
    Route::post('eventdesc/update/{id}', 'EventDescController@update')->name('eventdesc.update.{id}');
    Route::get('eventdesc/editar/{id}', 'EventDescController@edit')->name('eventdesc.editar.{id}');
    Route::get('eventdesc/delete/{id}', 'EventDescController@destroy')->name('eventdesc.delete.{id}');

    // Rotas de event
    Route::get('event', 'EventController@index')->name('event');
    Route::post('event/reorder', 'EventController@sortable')->name('event.reorder');
    Route::post('event/store', 'EventController@store')->name('event.store');
    Route::post('event/store/{id}', 'EventController@store')->name('event.store.{id}');

    // Rotas de event description
    Route::get('campaignsdesc', 'CampaignsDescController@index')->name('campaignsdesc');
    Route::post('campaignsdesc/reorder', 'CampaignsDescController@sortable')->name('campaignsdesc.reorder');
    Route::post('campaignsdesc/store', 'CampaignsDescController@store')->name('campaignsdesc.store');
    Route::post('campaignsdesc/update/{id}', 'CampaignsDescController@update')->name('campaignsdesc.update.{id}');
    Route::get('campaignsdesc/editar/{id}', 'CampaignsDescController@edit')->name('campaignsdesc.editar.{id}');
    Route::get('campaignsdesc/delete/{id}', 'CampaignsDescController@destroy')->name('campaignsdesc.delete.{id}');

    // Rotas de event
    Route::get('campaigns', 'CampaignsController@index')->name('event');
    Route::post('campaigns/reorder', 'CampaignsController@sortable')->name('campaigns.reorder');
    Route::post('campaigns/store', 'CampaignsController@store')->name('campaigns.store');
    Route::post('campaigns/store/{id}', 'CampaignsController@store')->name('campaigns.store.{id}');

    // Rotas de campaigns description
    Route::get('campaignsdesc', 'CampaignsDescController@index')->name('campaignsdesc');
    Route::post('campaignsdesc/reorder', 'CampaignsDescController@sortable')->name('campaignsdesc.reorder');
    Route::post('campaignsdesc/store', 'CampaignsDescController@store')->name('campaignsdesc.store');
    Route::post('campaignsdesc/update/{id}', 'CampaignsDescController@update')->name('campaignsdesc.update.{id}');
    Route::get('campaignsdesc/editar/{id}', 'CampaignsDescController@edit')->name('campaignsdesc.editar.{id}');
    Route::get('campaignsdesc/delete/{id}', 'CampaignsDescController@destroy')->name('campaignsdesc.delete.{id}');

    // Rotas de campaigns
    Route::get('campaigns', 'CampaignsController@index')->name('event');
    Route::post('campaigns/reorder', 'CampaignsController@sortable')->name('campaigns.reorder');
    Route::post('campaigns/store', 'CampaignsController@store')->name('campaigns.store');

app/Http/Controllers/Admin/AboutController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entities\About;
use App\Http\Controllers\Controller;
use App\Services\StandardService;
use Illuminate\Http\Request;
use Redirect;
use Session;

class AboutController extends Controller {

    /**
     * @var StandardService
     */
    protected $standard;

    public function __construct(StandardService $standard) {
        $this->standard = $standard;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        $item = About::get()->first();
        return view('admin.about.index', compact('item'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     *
     * @return \Illuminate\Http\Response
     */
    // SALVANDO
    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request, $id = 0) {
        try {

            if ($id == 0) {
                $item = new About;
            } else {
                $item = About::find($id);
            }


            $item->title_about = $request->input('title_about');
            
            $item->text_about = $request->input('text_about');
            
            $item->textcx = $request->input('textcx');
            
            $item->textfr = $request->input('textfr');
            

            $item->save();

            Session::flash('success', 'Item criado com sucesso!');
        } catch (ValidatorException $e) {

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
        return Redirect::to('/admin/about')->with('status', 'Post realizado com sucesso!');
    }


    /**
     * @param Request $request
     * @return int
     */
    public function sortable(Request $request) {
        $this->standard->doReorder($request->input('items'), true, $this->repository);
        return 2;
    }

   

}

resources/views/admin/about/banners_caxias/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Banners > Editar</h1>
@stop


@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Editar Campos</h3>
            </div>
            <form action="{{ route('admin.bannerscx.update.{id}', array($item->id)) }}" method="POST" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <div class="box-body">
                    <div class="col-xs-4">
                        <div class="form-group">
                            <label for="image">Imagem:</label>
                            <div class="upload">
                                <div class="btn btn-primary">Atualizar Imagem</div>
                                <input type="file" class="input-file" id="image" name="file_image" /><br>
                                @if (!empty($item->id))
                                (<a href="{{ asset('_files/bannerscx/' . $item->image) }}" title="ver imagem atual" target="_blank">Ver Imagem Atual</a>)
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="box-footer">
                    <button class="btn btn-success btn-send pull-right">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('vendor/adminlte/css/main.css')}}">
@stop

resources/views/admin/about/banners_caxias/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Banners</h1>
@stop


@section('content')
<div class="row">
    <div class="col-md-8 ">
        <div class="box ">
            <div class="box-header with-border">
                @if (!empty($items))
                <h3 class="box-title"><span style="vertical-align: inherit;">Lista de banners</span></h3>
                @else
                <h3 class="box-title"><span style="vertical-align: inherit;">Nenhum um item cadastrado</span></h3>
                @endif
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
                @endif
                <table id="tabela" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Imagem</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($items as $item)
                        <tr>
                            <td>{{$item->id}}</td>
                            <td><img width="80" src="{{asset('_files/bannerscx/'.$item->image)}}"></td>
                            <td>
                                <div class="btn-group">
                                    <a type="button" class="btn btn-success" href="{{route('admin.bannerscx.editar.{id}', array($item->id))}}" data-toggle="tooltip" data-original-title="Editar"><i class="fa fa-pencil"></i></a>
                                    <a type="link"  class="btn btn-danger" href="{{route('admin.bannerscx.delete.{id}', array($item->id))}}" data-toggle="tooltip" data-original-title="Deletar"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Imagem</th>
                            <th>Ações</th>
                        </tr>
                    </tfoot>
                </table>
                <!-- /.row -->
            </div>
            <!-- ./box-body -->
        </div>
        <!-- /.box -->
    </div>
    <div class="col-xs-12 col-md-4">
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title">Adicionar Banner</h3>
            </div>
            <form action="{{ route('admin.bannerscx.store') }}" class="form-table-list" method="POST" enctype="multipart/form-data">
                {!! csrf_field() !!}
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="image">Imagem:</label>
                                <div class="upload">
                                    <div class="btn btn-primary">Adicionar Imagem</div>
                                    <input type="file" class="input-file" id="image" name="file_image" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button class="btn btn-success btn-send pull-right">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>    
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('vendor/adminlte/css/main.css')}}">
@stop

@section('js')
<script>
    $('#tabela').DataTable({
        language: {
            emptyTable: "Nenhum registro encontrado",
            info: "Mostrando de _START_ até _END_ de _TOTAL_ registros",
            infoEmpty: "Mostrando 0 até 0 de 0 registros",
            infoFiltered: "(Filtrados de _MAX_ registros)",
            infoPostFix: "",
            infoThousands: ".",
            lengthMenu: "_MENU_ resultados por página",
            loadingRecords: "Carregando...",
            processing: "Processando...",
            zeroRecords: "Nenhum registro encontrado",
            search: "Pesquisar",
            paginate: {
                next: "Próximo",
                previous: "Anterior",
                first: "Primeiro",
                last: "Último"
            },
            aria: {
                sortAscending: ": Ordenar colunas de forma ascendente",
                sortDescending: ": Ordenar colunas de forma descendente"
            }
        }
    });


</script>
@stop